AllCops:
  TargetRubyVersion: 2.7

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 7

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
